### ISSUE TITLE
PT-H500 support

### ISSUE THREAD

**Issue by Bintux** [clarkewd/ptouch-print#3]
Hi just bought the PT-H500 and I would like to help if I can to add the support for this device. 

That's what I see when executing lsusb
Bus 003 Device 004: ID 04f9:205e Brother Industries, Ltd

**Comment by clarkewd** [comment]
Dominic is the real expert with this software so you may want to reach out to him if you'd like to contribute. It's also worth reading over his website which is linked in the README, and he has a contact page on his site, too. Otherwise you're welcome to submit pull requests here and we'll incorporate them.

I have the PT-P700 and Dominic has a different model. I most of the code for the different models has come from community contributions. So you'd need to work out the parameters for the PT-H500 and implement those. Brother has good documentation, see the [Raster Command Reference for the PT-H500](https://support.brother.com/g/b/manualtop.aspx?c=us&lang=en&prod=h500eus). I'd suggest using the code for the most similar model you can find in this repo and then working to make adjustments where needed.

**Comment by Bintux** [comment]
Thank you for the fast reply and the link to the documentation. Since it is titled : "Raster Command Reference PT-H500/P700/E500 Version 1.10" I am hopeful I can look at the implementation to the P700 and start from there.

**Comment by Bintux** [comment]
I compared the H500 and E500 just on a specs level and they look quite similar and thus I tried and as expected I was successful with copying the E500 line and adjusting the PID to that of the H500 in the libtouch. I'll check with Dominic how to test and integrate this.

{0x04f9, 0x205e, "PT-H500", 128, 180, FLAG_RASTER_PACKBITS},

**Comment by clarkewd** [comment]
Excellent! Thank you for contributing!
